# explains everything - https://dwdraju.medium.com/how-deployment-service-ingress-are-related-in-their-manifest-a2e553cf0ffb
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    # for host to work need to add text in file C:\Windows\system32\drivers\etc\hosts
    # ingress-ip search.discovervegan.lt
    - host: search.discovervegan.lt
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 8080
