apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service-deployment
  labels:
    app: file-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service-app
  template:
    metadata:
      labels:
        app: file-service-app
    spec:
      containers:
        - name: file-service-app
          image: file-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: discover-vegan-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: discover-vegan-secrets
                  key: AWS_SECRET_ACCESS_KEY