server:
  port: 8080
spring:
  data:
    mongodb:
      host: mongodb-service
      port: 27017
      database: search-service
web:
  access-control-allow-origin: "*"
  access-control-allow-headers: "*"
  access-control-allow-methods: "OPTIONS, POST, GET, PATCH, DELETE"