server:
  port: 8081

aws:
  bucket: discover-vegan-images
  region: eu-north-1
#spring:
#  datasource:
#    url: jdbc:h2:file:C:/Dev/h2databases/file-service
#    driverClassName: org.h2.Driver
#    username: admin
#  h2:
#    console:
#      enabled: true
#      path: /database
#      settings:
#        web-allow-others: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update