server:
  port: 8081

aws:
  bucket: discover-vegan-images
  region: eu-north-1
web:
  access-control-allow-origin: "*"
  access-control-allow-headers: "*"
  access-control-allow-methods: "OPTIONS, POST, GET, PATCH, DELETE"