server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authentication-service
web:
  access-control-allow-origin: "*"
  access-control-allow-headers: "*"
  access-control-allow-methods: "OPTIONS, POST, GET, PATCH, DELETE"