apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
  labels:
    app: search-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service-app
  template:
    metadata:
      labels:
        app: search-service-app
    spec:
      containers:
        - name: search-service-app
          image: search-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: secrets.googleApiKey
              valueFrom:
                secretKeyRef:
                  name: discover-vegan-secrets
                  key: GOOGLE_API_KEY